### ISSUE TITLE
Initial Build

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-html-table-source#1]
For the initial build, the integration should take a url of a page containing a table. It will then output the file as a csv. 

```
"config":{
   "url": "www.example.com"
}
```

Additionally, a timestamp for when the activity is occurring should be appended to each record.

**Resources**
https://www.npmjs.com/package/node-table-to-csv

**Comment by jlaneve** [comment]
@benjamingregory pull request was merged, so this can be closed now
